### ISSUE TITLE
[Combinator] Display the %dps difference with the best set

### ISSUE THREAD

**Issue by Melekus** [SimCMinMax/herodamage#31]
It would help getting an idea on how a specific build fares against the top simming one, because ranks aren't all that great at doing that.

It could either show the % difference with top build altogether, or with the highest gear displayed with the current settings. Or even use a toggle option to switch between the two.

**Comment by Mystler** [comment]
Added in https://github.com/SimCMinMax/herodamage/commit/50a37c39ce5877e0e7bf4890a10be5e361ab6948.
