### ISSUE TITLE
[Site] Add a link to the github page

### ISSUE THREAD

**Issue by Melekus** [SimCMinMax/herodamage#32]
Currently the only links to the github are in the changelog page and only point at specific commits. Would be nice to have it displayed somewhere else : either in the FAQ, cleanly on the changelog page, or even in the About section of the top bar with the links to the FAQ/Blog/Changelog

**Comment by aethys256** [comment]
Added in the footer like most websites.
Implemented in https://github.com/SimCMinMax/herodamage/commit/42c2a0c28966aba6fe0b1baf7e7a3ff9a0fdb10e
