### ISSUE TITLE
[Page] Fix Class Collection Layouts

### ISSUE THREAD

**Issue by Mystler** [SimCMinMax/herodamage#34]
Subpages added to a class collection currently have the class-index forced, just like the index. They should probably have "page" layout by default.

**Comment by aethys256** [comment]
Fixed in https://github.com/SimCMinMax/herodamage/commit/5258dee39821611474bab36bad6236b6a6e177b1 and https://github.com/SimCMinMax/herodamage/commit/cfdb9d4e07724fa32a1cd0e2be2e36fe8569279f
