### ISSUE TITLE
[Scripts] Switch from CSV to JSON output

### ISSUE THREAD

**Issue by Mystler** [SimCMinMax/herodamage#36]
Since CloudFlare compression suggests that we should move from CSV to JSON data files and the parser skeleton is in place, we should refactor the scripts for those outputs.

Until then, a converter may do.

**Comment by aethys256** [comment]
Implement in https://github.com/Ravenholdt-TC/SimcScripts/compare/69dccc3...1550eff and https://github.com/SimCMinMax/herodamage/compare/a508d03...0ff81b5
