### ISSUE TITLE
[Trinkets] Add new Ulduar Timewalking (930-945) Trinkets

### ISSUE THREAD

**Issue by Oxev** [SimCMinMax/herodamage#44]
Add timewarped versions of Ulduar Trinkets, such as Wrathstone and Pyrite Infuser. Wrathstone is giving 10k agility/strength for 20 seconds on a 2 minute cooldown at 930 ilvl.

**Comment by aethys256** [comment]
Thanks for the report, will do.

**Comment by aethys256** [comment]
Implement in https://github.com/Ravenholdt-TC/SimcScripts/commit/6f93a875e8928cdc248a4f649f37735b8eab9069 and https://github.com/Ravenholdt-TC/SimcScripts/commit/cc9948b096bbe59ff6da983b6174d9b42d0e1f0e :)
Will be part of the next update.
