### ISSUE TITLE
missing trinket from t21, t20 and t19 for rouges

### ISSUE THREAD

**Issue by SirSkylos** [SimCMinMax/herodamage#45]
the trinket http://www.wowhead.com/item=144477/splinters-of-agronox&bonus=1826:1497 doesnt appear to be on the list for rogues  under the the trinket section

**Comment by aethys256** [comment]
Implemented in https://github.com/Ravenholdt-TC/SimcScripts/commit/ba12eccbaed4ddb747c1ff2c1a48b22fef5bc3a9 :)
Will be part of the next update.
